CHANGELOG.md, lisp/_prepare.el, lisp/core/install.el, lisp/core/reinstall.el, lisp/core/uninstall.el
For #9.
This patch will avoid `(eask-pkg-init)` function call until we need to.
Result:
```diff
Installing 1 specified package...
- Loading package information... done
- Skipping dash (20220516.2220)... already installed
(Total of 0 package installed, 1 skipped)
```
=> Avoid loading package info unless it's needed

cmds/util/upgrade-eask.js
The scope must be prefixed by @ in the error explanation so the command can be copy-pasted.
=> fix(upgrade): add missing @

CHANGELOG.md, lisp/_prepare.el, lisp/core/info.el
For #10
Example output in smartparens (with `-pkg.el` file):
```diff
Running Eask in the development environment
Press Ctrl+C to cancel.
Executing script inside Emacs...
✓ Checking Emacs version 29.0.50... done!
✓ Checking system windows-nt... done!
+ ✓ Try constructing the package-descriptor (smartparens-pkg.el)... succeed!
✓ Loading Eask file in c:/Users/path/to/smartparens/Eask... done!
smartparens (1.11.0) | deps: 2 | devDeps: 21
Automatic insertion, wrapping and paredit-like navigation with user defined pairs.
entry: smartparens.el
kind: single
dist
.total-files: 1
.unpacked-size: 391k
dependencies:
cl-lib (0.3)
dash   (2.13.0)
devDependencies:
f             (latest)
ert-runner    (latest)
undercover    (latest)
shut-up       (latest)
ruby-mode     (latest)
racket-mode   (latest) …
```
=> Read -pkg.el file prior to package-file while exists

lisp/core/exec.el
```
(eask-with-verbosity 'debug
...)
```
Is meaningless here since `exec` will ignore all options from yargs.
=> Use silent instead verbosity

lisp/core/exec.el
Commander is a must for elisp executable.
=> revert: commander arguments

CHANGELOG.md, cmds/core/exec.js, lisp/core/exec.el, src/util.js
Execute `exec` in the node layer. This mimic Cask's behaviour
https://github.com/cask/cask/blob/bd8aa8297aba1a34f0ff55fd517b431fd0d549cf/bin/cask#L52-L54
This should resolve #12 completely.
=> Move exec command to node layer

CHANGELOG.md, cmds/core/lint.js, cmds/core/test.js, cmds/lint/declare.js, cmds/lint/indent.js, cmds/lint/package.js, cmds/lint/regexps.js, docs/content/en/Getting Started/Commands and options.md, eask, lisp/lint/checkdoc.el, lisp/lint/declare.el, lisp/lint/elint.el, lisp/lint/elsa.el, lisp/lint/indent.el, lisp/lint/package.el, lisp/lint/regexps.el, lisp/test/ert-runner.el, test/commands/local/run.sh, test/commands/test/buttercup/run.sh, test/commands/test/ert-runner/run.sh, test/commands/test/ert/run.sh
1. Move all `test` commands to live under command `eask test`
```
PS C:\Users\XXX\path\to\project> eask test
test <type>
run test
Commands:
test buttercup [files..]    run buttercup tests
test ert-runner [files..]   run ert tests using ert-runner
test ert [files..]          run ert tests
Options:
...
```
2. Move all `lint` commands to live under command `eask lint`
```
PS C:\Users\XXX\path\to\project> eask lint
lint <type>
run linter
Commands:
lint checkdoc [files..]   run checkdoc
lint declare [files..]    run check-declare
lint elint [files..]      run elint
lint elsa [files..]       run elsa
lint indent [files..]     lint the package using indent-lint
lint package [files..]    lint the package using package-lint
lint regexps [files..]    run relint
Options:
...
```
=> code: move commands to it's subcommand

test/mini.emacs.pkg/Eask, test/mini.emacs.pkg/mini.emacs.pkg.el
`eask lint package` was broken without me noticing (fixed in 2165c6bde14bb65979922fa32081089facd80d54), add more tests to prevent this situation happens again.
=> Add regression tests for linting module

lisp/extern/package-recipe.el, test/commands/local/run.sh, test/development/compat.el
It seems like `time-convert` is missing in Emacs 26.x
=> time-convert compat check

.dir-locals.el, docs/content/en/FAQ/_index.md
This commit adds a reference to #39 in the FAQ.
It also adds `.dir-locals.el` for column width in Markdown files. I’m not sure which value you’re using on your setup --- mine is 70 by default, so definitively not what I can see in the markdown files. Let me know if I have to change that.
=> Add bug-reference-bug-mode reference to FAQ

CHANGELOG.md, cmds/core/run.js, lisp/core/archives.el, lisp/core/run.el, test/commands/local/run.sh
You can now use
```
$ eask archives --all
```
to list out all archives that are available!
Example output:
```
...
List all available archives:
gnu           https://elpa.gnu.org/packages/                    0
nongnu        https://elpa.nongnu.org/nongnu/                   0
celpa         https://celpa.conao3.com/packages/                0
jcs-elpa      https://jcs-emacs.github.io/jcs-elpa/packages/    0
marmalade     https://marmalade-repo.org/packages/              0
melpa         https://melpa.org/packages/                       0
melpa-stable  https://stable.melpa.org/packages/                0
org           https://orgmode.org/elpa/                         0
shmelpa       https://shmelpa.commandlinesystems.com/packages/  0
(Total of 9 archives available)
```
=> feature: Adapt `-a`/`--all` option for archives command

CHANGELOG.md, cmds/core/init.js
Update `init` command after #68.
Now we can create multiple Eask-file in the same directory.
=> feat: Handle multiple Eask-files for `init` command

CHANGELOG.md, lisp/lint/keywords.el
Keywords lint weren't able to detect valid keyword, this fixes the issue.
=> fix: Keyword lint undetected

CHANGELOG.md, lisp/_prepare.el, test/development/compat.el
We not use function `locate-dominating-file` to search for valid Eask-file. This will make behaviour similar to .dir-locals.el` file.
=> feature(_prepare.el): Improve Eask-file loader to search file upward

lisp/_prepare.el
Make directive `source` accept symbol.
```elisp
(source "gnu")
(source 'gnu)  ; accept symbol
```
=> chore(_prepare.el): Make source directive accept symbol

CHANGELOG.md, cmds/test/activate.js, docs/content/en/Getting Started/Basic Usage.md, docs/content/en/Getting Started/Commands and options.md, lisp/test/activate.el, test/commands/local/run.sh
```
eask activate [files..]
```
is now
```
eask test activate [files..]
```
=> chore(activate): Move command `activate` under test subcommand

CHANGELOG.md, cmds/checker/check-eask.js, lisp/_prepare.el, lisp/checker/check-eask.el, src/util.js
Add option `--output` to write log to file:
```
eask check-eask -o log.txt
```
=> feat: Add option `--output` to output log for Eask checker

lisp/_prepare.el
minor changes
This should avoid name collision `eask`.
=> fix(_prepare.el): Load Eask-file explicitly

lisp/_prepare.el, lisp/extern/package-build.el
Resolved after https://github.com/melpa/package-build/pull/72.
We can remove the unnecessary hassle regarding Windows tar (bsd) executable.
=> chore(package-build): Remove tar version string

CHANGELOG.md, lisp/_prepare.el
=> fix(_prepare.el): Resolve infinite recursion in exec-path setup

cmds/core/exec-path.js, cmds/core/files.js, cmds/core/load-path.js, docs/content/en/Getting Started/Basic Usage.md, docs/content/en/Getting Started/Commands and options.md, lisp/core/exec-path.el, lisp/core/exec.el, lisp/core/files.el, lisp/core/load-path.el, test/commands/local/run.sh
New behavior for these commands:
- `eask files`
- `eask path` or `eask exec-path`
- `eask load-path`
You can now pass in `[PATTERN..]` to perform the search.
```
$ eask files *.el
```
=> feat: Add capability to search through path

.github/workflows/docs.yml, CHANGELOG.md, docs/content/en/DSL/_index.md, lisp/_prepare.el, test/checker/dsl/Eask
Compatible to Cask's `package-descriptor`,
```elisp
(package-descriptor "foo-pkg.el")
```
=> feat(DSL): Add package-descriptor

.gitignore, CHANGELOG.md, cmds/core/emacs.js, cmds/core/eval.js, cmds/core/exec.js, cmds/core/run.js, lisp/core/eval.el, src/util.js, test/commands/local/run.sh
For #128.
- https://github.com/nodejs/node/issues/5060
- https://github.com/nodejs/node/issues/10461
=> fix(process): Workaround for arguments that contain whitespaces

cmds/core/exec.js, test/commands/exec/Eask, test/commands/exec/run.sh, test/commands/exec/test/test-dummy.el
It's fix on local machine, however, GHA act differently.
Follow up fix for #129.
=> fix(arg): Investigate whitespace arguments error in GHA

lisp/help/link/add/error, lisp/help/link/add/success, lisp/link/add.el
For #131.
Edit: Drop Eask-file as an option since we would eventually need a `-pkg.el` file.
=> feat(link/add): Don't link when no -pkg.el file

CHANGELOG.md, cmds/core/init.js, docs/content/en/Getting Started/Basic Usage.md, docs/content/en/Getting Started/Commands and options.md, lisp/_prepare.el, lisp/help/init/cask, lisp/init/cask.el, lisp/lint/checkdoc.el, lisp/lint/declare.el, lisp/lint/indent.el
For #141. Add the options,
```
$ eask init --from cask [files..]
```
Another feature, the help instruction now look like this:
```
''                                                           ''
Make sure you have a valid Cask-file in your directory
Or specify Cask-file explicitly, like:
$ eask init --from=cask /path/to/Cask
''                                                           ''
```
Expect for improvements.
=> feat(cask): Add option to convert Cask to Eask

CHANGELOG.md, cmds/lint/keywords.js, cmds/lint/license.js, docs/content/en/Getting Started/Commands and options.md, lisp/lint/license.el, test/commands/local/run.sh
New command to check for license(s),
```
eask lint license
```
Inspired from [melpazoid](https://github.com/riscy/melpazoid)'s license checker.
=> feat(lint): Add license linter

CHANGELOG.md, lisp/clean/all.el
Example output,
```
Try constructing the package-descriptor (openai.el)... succeeded!
Loading Eask file in d:/_workspace/openai/Eask... done!
Cleaning workspace... skipped
Cleaning byte-compile files... skipped
Cleaning dist... done
Cleaning autoloads file... skipped
Cleaning pkg-file... skipped
Cleaning log files... skipped
(Total of 1 task cleaned, 5 skipped)
```
=> feat(clean): Improve messages while task cleaning all

CHANGELOG.md, cmds/core/status.js, docs/content/en/Getting Started/Basic Usage.md, docs/content/en/Getting Started/Commands and options.md, eask, lisp/_prepare.el, lisp/core/emacs.el, lisp/core/status.el, src/util.js, test/commands/local/run.sh
For #123.
Move the header information to a command `eask status`.
=> feat: Use standard output

CHANGELOG.md, cmds/core/emacs.js, docs/content/en/Getting Started/Finding Emacs.md, src/env.js, src/util.js
Make use of environment PATH, `EMACS` and `EASK_EMACS`.
=> feat: Use environment PATH to specify Emacs version to use

CHANGELOG.md, docs/content/en/Development-API/_index.md, docs/content/zh-TW/Development-API/_index.md, lisp/_prepare.el, lisp/core/install-deps.el, lisp/core/refresh.el, lisp/lint/package.el
Example,
```
Loading package information...
- [1/2] Downloading gnu (http://elpa.gnu.org/packages/)... done v
- [2/2] Downloading melpa (http://melpa.org/packages/)... done v
done v
```
=> feat: Print archives progress

CHANGELOG.md, cmds/core/run.js, lisp/core/run.el
Closes #103 and #104.
Uses the workaround mentioned in https://github.com/vercel/pkg/issues/1356#issuecomment-1145048409.
=> fix(vcpkg): Use workaround for MODULE_NOT_FOUND error

CHANGELOG.md, cmds/core/docker.js
Shoot a single command:
```sh
$ eask docker 26.1 info   # Same as `eask info` but in the container!
```
Enter docker container without leaving immediately:
```sh
$ eask docker 26.1
```
=> feat(docker): Enter docker directly when no arguments

PKGBUILD, docs/content/Getting-Started/Install-Eask/_index.en.md, package.json
Fixes: https://github.com/emacs-eask/cli/issues/215
---------
Two points I'm not sure about:
1. Is putting `PKGBUILD` to the top dir okay?
2. Is `pkg` not being among deps in `package.json` an explicit decision, or an omission that needs to be fixed? In the latter case I'd add a commit that fixes this and would remove the explicit installation of `pkg` that is part of `PKGBUILD` and the `Building from source` sections *(in this PR)*.
=> Add PKGBUILD and building instructions

cmds/core/loc.js, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, lisp/core/load.el, lisp/core/loc.el, test/commands/local/run.sh
Example output:
```
$ eask loc
- Skipping markdown-mode (20240107.831)... already installed X
Retrieving LOC information... done v
|-------------------------------------------------|-------|------------|
| File                                            | Lines | Characters |
|-------------------------------------------------|-------|------------|
| d:/_workspace/_eask/openai/openai.el            | 257   | 8604       |
| d:/_workspace/_eask/openai/openai-audio.el      | 116   | 4644       |
| d:/_workspace/_eask/openai/openai-chat.el       | 124   | 4404       |
| d:/_workspace/_eask/openai/openai-completion.el | 172   | 6483       |
| d:/_workspace/_eask/openai/openai-edit.el       | 93    | 3317       |
| d:/_workspace/_eask/openai/openai-embedding.el  | 73    | 2702       |
| …
```
=> feat: Add loc command

.github/workflows/checker.yml, CHANGELOG.md, Makefile, cmds/core/analyze.js, docs/content/Getting-Started/Basic-Usage/_index.en.md, docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, eask, lisp/_prepare.el, lisp/core/analyze.el, lisp/help/core/analyze, test/checker/dsl/run.sh, test/checker/metadata/run.sh
```bash
$ eask check-eask
```
to
```bash
$ eask analyze
```
=> feat: Rename command `check-eask` to `analyze`

PKGBUILD
I accidentally made the building command part of `prepare()` function which is not correct as various `pacman` options that a user may want to use operate on these functions. Let's fix that.
=> PKGBUILD: move building command to `build()` function

CHANGELOG.md, cmds/core/emacs.js, docs/content/Development-API/_index.en.md, docs/content/Development-API/_index.zh-tw.md, lisp/_prepare.el
A bug in https://github.com/emacs-tree-sitter/elisp-tree-sitter/pull/275.
=> fix: Don't pollute outer programs

CHANGELOG.md, cmds/core/docs.js, docs/content/Getting-Started/Basic-Usage/_index.en.md, docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, lisp/_prepare.el, lisp/core/docs.el, lisp/help/core/concat, lisp/help/core/docs, test/commands/local/run.sh
For #82.
This is far from a useful command, but this is the first step. I'm looking forward to improving this command in the future. 🤔
=> feat: Add docs command

PKGBUILD
Node puts scripts to some ELF sections, so we can't strip these. Strictly speaking, judging by the offsets they seem to be put into .dynstr section, but leaving that section unstripped doesn't make the error
Pkg: Error reading from file
…go away. Unless someone is motivated to dig into the list of sections to be put to `STRIP_BINARIES`, let's just disable it.
Fixes: https://github.com/emacs-eask/cli/issues/248
=> PKGBUILD: avoid stripping the `eask` binary

CHANGELOG.md, cmds/core/recompile.js, docs/content/Getting-Started/Basic-Usage/_index.en.md, docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, lisp/_prepare.el, lisp/core/compile.el, lisp/core/recompile.el, test/commands/local/run.sh
=> feat(cmds): Add recompile command

lisp/lint/declare.el
Fixes #271 
* --strict formats warnings like errors and exits with status 1
* extra message output of `check-declare-file` is hidden
* set allow-errors to 'always' in code so that all files are linted
After the change:
```shell
> ~/git/eask-cli/bin/eask lint declare --strict
`js-comint.el` with check-declare
js-comint.el:148:Warning (check-declare): said ‘nvm--find-exact-version-for’ was defined in .eask/31.0.50/elpa/nvm-20240921.1901/nvm.el: arglist mismatch
`test-js-comint.el` with check-declare
No issues found
(Total of 2 files have checked)
```
The output line is formatted like an error and the exit code is 1.
Perhaps 'Warning (check-declare)' should be removed from the output?
e.g. this seems like a better message
```
js-comint.el:148: ‘nvm--find-exact-version-for’ was defined in …
```
=> Fix: match behavior of declare linter to checkdoc

cmds/core/install-deps.js, docs/content/Getting-Started/Basic-Usage/_index.en.md, docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md, eask, lisp/core/archives.el, lisp/help/link/add/success/eask, lisp/help/link/add/success/pkg, lisp/help/run/script, lisp/link/add.el, lisp/link/delete.el
Just fixing some typos I noticed while adding exit code tests.
=> Fix some typos in help messages and command doco

CHANGELOG.md, docs/content/Development-API/_index.en.md, docs/content/Development-API/_index.zh-tw.md, lisp/_prepare.el, lisp/core/cat.el, lisp/core/docs.el, lisp/core/loc.el, lisp/core/package.el, lisp/format/elfmt.el, lisp/format/elisp-autofmt.el, lisp/generate/ignore.el, lisp/generate/license.el, lisp/generate/test/buttercup.el, lisp/generate/test/ecukes.el, lisp/generate/test/ert-runner.el, lisp/init/cask.el, lisp/init/eldev.el, lisp/init/keg.el, lisp/lint/elisp-lint.el, lisp/lint/elsa.el, lisp/lint/package.el, lisp/lint/regexps.el, lisp/test/buttercup.el, lisp/test/ecukes.el, lisp/test/ert-runner.el, lisp/test/melpazoid.el
For https://github.com/emacs-eask/eask/issues/6.
=> feat(core): Lazy install on required packages

lisp/test/ert.el, test/commands/test/ert/run.sh, test/commands/test/ert/test-nil-message/ert-test.el
From the doco: `(message nil)` can be used to clear the minibuffer.
However, `eask-test-ert--message` is advised on `message` when running `eask test ert` and passes all `message` args to `format`, which requires a format string.
The provided test incorrectly fails with a signal (it should succeed)
```elisp
(ert-deftest ert-test-1 ()
(should-not (message nil)))
```
The backtrace is like
```
Test ert-test-1 backtrace:
format(nil)
apply(format nil)
(string-match-p "^[ ]+FAILED " (apply #'format args))
(cond ((string-match-p "^[ ]+FAILED " (apply #'format args)) (eask-m
(let ((eask-test-ert--message-loop t)) (cond ((string-match-p "^[ ]+
(if eask-test-ert--message-loop (apply fnc args) (let ((eask-test-er
eask-test-ert--message(#<subr message> nil)
apply(eask-test-ert--message #<subr …
```
=> Fix `eask-test-ert--message` breaks tests which trigger minibuffer

.github/workflows/build.yml
=> ci: No need to explicit install pkg globally

docs/content/Contributing/Developing-Eask/_index.en.md, docs/content/Contributing/Developing-Eask/_index.zh-tw.md, docs/content/Development-API/_index.en.md, docs/content/Development-API/_index.zh-tw.md, docs/content/Getting-Started/Advanced-Usage/_index.en.md, docs/content/Getting-Started/Advanced-Usage/_index.zh-tw.md, docs/content/Getting-Started/Basic-Usage/_index.en.md, docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, docs/content/Getting-Started/Finding-Emacs/_index.en.md, docs/content/Getting-Started/Finding-Emacs/_index.zh-tw.md, docs/content/Getting-Started/Install-Eask/_index.en.md, docs/content/Getting-Started/Install-Eask/_index.zh-tw.md, docs/content/Getting-Started/Quick-Start/_index.en.md, docs/content/Getting-Started/Quick-Start/_index.zh-tw.md
The command can be copied from GitHub into CLI with no modification
=> remove `$ ` prefix from all Markdown documentation commands

.github/workflows/docs.yml
Suggested change in other PR. See review comments on code.
=> Fix: docs CI workflow should only publish when on master

cmds/create/el-project.js, cmds/create/package.js, docs/content/Getting-Started/Commands-and-options/_index.en.md, docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md, lisp/_prepare.el, lisp/create/el-project.el
Add command for https://github.com/Kyure-A/el-project
```
eask create el-project
```
=> feat(create): Add new command for el-project
