- lisp/core/compile.el
- lisp/core/list.el
- lisp/core/package.el
> Avoid more loading package info

- README.md
> Add logo on top right

- lisp/core/exec.el
> Avoid loading package info for exec

- lisp/core/exec.el
> Improve comment in exec

- lisp/core/package.el
- lisp/extern/package-build.el
> Avoid mtime

- .github/workflows/checker.yml
- CHANGELOG.md
- lisp/_prepare.el
- lisp/core/exec.el
- package-lock.json
- src/env.js
- src/util.js
> Inhibit color in DUMB terminal

- CHANGELOG.md
- lisp/extern/package-build.el
- lisp/extern/package-recipe.el
Revert #30. 
Follow up https://github.com/cask/cask/pull/570
> Add implementation for package-build--get-timestamp

- lisp/_prepare.el
- lisp/core/create.el
> fix(create): honour version and emacs_version

- .github/workflows/checker.yml
- .github/workflows/emacs.yml
- .github/workflows/exec.yml
- .github/workflows/global.yml
- .github/workflows/install.yml
- .github/workflows/local.yml
- .github/workflows/options.yml
- .github/workflows/outdated_upgrade.yml
- .github/workflows/search.yml
- .github/workflows/test_buttercup.yml
- .github/workflows/test_ert-runner.yml
- .github/workflows/test_ert.yml
- CHANGELOG.md
- Makefile
- README.md
- docs/content/en/Getting Started/Commands and options.md
- docs/content/en/_index.md
- eask
- lisp/_prepare.el
- src/util.js
- test/options/.gitignore
- test/options/Eask
- test/options/run.sh
Major changes:
* Remove two options contradict to default settings, `--no-timestamps` and `--no-log-level` (#48)
* Add new option `--elapsed-time`, `--et` (#48)
> feat(elasped): impls elapsed time

- CHANGELOG.md
- lisp/extern/package-recipe.el
- test/development/compat.el
Follow up with https://github.com/cask/cask/pull/571
> fix(extern): Replace time-convert to compatible with older version

- CHANGELOG.md
- lisp/test/buttercup.el
Propose fix from https://github.com/jorgenschaefer/emacs-buttercup/pull/217
> fix(buttercup): use propose fix

- lisp/_prepare.el
- lisp/extern/package-build.el
- test/checker/dsl/run.sh
- test/checker/metadata/run.sh
- test/color/run.sh
- test/commands/emacs/run.sh
- test/commands/exec/run.sh
- test/commands/global/run.sh
- test/commands/install/run.sh
- test/commands/local/run.sh
- test/commands/outdated_upgrade/run.sh
- test/commands/search/run.sh
- test/commands/test/buttercup/run.sh
- test/commands/test/ert-runner/run.sh
- test/commands/test/ert/run.sh
- test/error/run.sh
- test/options/run.sh
This will trigger error in GitHub Actions.
References: https://stackoverflow.com/questions/3474526/stop-on-first-error
> test: Enable set -e

- lisp/_prepare.el
> fix(_prepare.el): Fix void eask-source -> eask-f-source

- docs/content/en/DSL/_index.md
- docs/content/en/Examples/Emacs Configuration.md
- docs/content/en/Examples/Package Development.md
- docs/content/en/Examples/Real project examples.md
- docs/content/en/Getting Started/Quick Start.md
Update documents after adding `script` directive.
> docs: Update Eask-file examples

- lisp/_prepare.el
- lisp/core/package.el
- lisp/extern/package-build.el
- lisp/extern/package-recipe.el
For https://github.com/melpa/package-build/issues/68
> chore(package-build): Obsolete package-build-expand-file-specs

- CHANGELOG.md
- Easkfile
- cmds/core/create.js
- cmds/create/elpa.js
- cmds/create/package.js
- docs/content/en/Contributing/Documentation.md
- docs/content/en/Development API/_index.md
- docs/content/en/Getting Started/Basic Usage.md
- docs/content/en/Getting Started/Commands and options.md
- docs/content/en/Getting Started/Directory Structure.md
- lisp/_prepare.el
- lisp/create/elpa.el
- lisp/create/package.el
- lisp/test/activate.el
- package-lock.json
❌ Before 
```sh
eask create <package-name>
```
✔️ Now
```sh
eask create package <package-name>  # alias pkg
```
1. New command `eask create elpa`
```sh
eask create elpa <elpa-name>
```
2. Directive `script` first argument accepts symbol
```elisp
(script "install" "xxx")
(script 'install "xxx")  ; this works now!
```
> feat: Add command to create ELPA project

- lisp/core/eval.el
- test/commands/local/run.sh
- test/development/compat.el
> fix: Correct eval command

- CHANGELOG.md
- cmds/clean/autoloads.js
- docs/content/en/Getting Started/Commands and options.md
- lisp/clean/all.el
- lisp/clean/autoloads.el
- lisp/core/autoloads.el
- test/commands/local/run.sh
Add command to clean autoloads file
```sh
eask clean autoloads
```
> feat: Add command to clean autoloads

- CHANGELOG.md
- cmds/clean/pkg-file.js
- docs/content/en/Getting Started/Commands and options.md
- lisp/clean/all.el
- lisp/clean/pkg-file.el
- test/commands/local/run.sh
Add command to clean pkg-file
```sh
eask clean pkg-file
```
> feat: Add command clean pkg-file

- cmds/checker/check-eask.js
- lisp/_prepare.el
- lisp/checker/check-eask.el
- lisp/clean/all.el
- lisp/core/install.el
- lisp/core/reinstall.el
- lisp/core/uninstall.el
- lisp/help/link/add
- lisp/link/add.el
- lisp/link/delete.el
Overall improvement for `link` command
> fix: Improve `link` command

- lisp/core/install.el
- lisp/core/reinstall.el
- lisp/core/uninstall.el
For https://github.com/ericdallo/jet.el/issues/1.
> fix: Package `x` is unavailable issue from snapshot

- .github/workflows/build.yml
> test(build.yml): Zip instead of tar

- README.md
- lisp/_prepare.el
- lisp/core/info.el
- test/commands/local/run.sh
> chore: Improve printing system information

- lisp/lint/elsa.el
- test/commands/local/run.sh
For https://github.com/emacs-elsa/Elsa/issues/194.
> fix(lint): Elsa command error

- lisp/_prepare.el
> fix(link): Display current version string

- lisp/lint/elsa.el
Mentioned in https://github.com/emacs-elsa/Elsa/pull/199.
> fix(lint/elsa): Fix wrong arguments error due to upstream changes

- CHANGELOG.md
- lisp/lint/checkdoc.el
- lisp/lint/elint.el
- lisp/lint/elisp-lint.el
- lisp/lint/elsa.el
- lisp/lint/indent.el
- lisp/lint/keywords.el
- lisp/lint/package.el
- lisp/lint/regexps.el
> fix: Allow linter list through all errors

- CHANGELOG.md
- lisp/_prepare.el
> fix(development): Omit nil value for conditions

- .github/workflows/build.yml
- .github/workflows/docs.yml
- docs/content/en/Development API/_index.md
- lisp/init/cask.el
> fix(init): Fix load path and basename on unix

- .github/workflows/checker.yml
- .github/workflows/link.yml
- .github/workflows/search.yml
- .github/workflows/test_ert-runner.yml
- .github/workflows/test_ert.yml
- .github/workflows/webinstall.yml
- webinstall/install.bat
- webinstall/install.sh
Install Eask with `curl`,
```
curl -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.sh | sh
```
```
run: curl.exe -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.bat | cmd /Q
```
> feat(webinstall): Add webinstall

- .github/workflows/webinstall.yml
- README.md
- docs/content/en/Getting Started/Install Eask.md
- webinstall/install.sh
> ci: Test webinstall

- CHANGELOG.md
- docs/content/en/DSL/_index.md
- docs/content/en/Development API/_index.md
- lisp/_prepare.el
- test/checker/dsl/Eask
Support new DSLs.
```elisp
(author "Your Name" "your.mail@gmail.com")
(license "GPLv3")
```
> feat(DSL): Add new DSL for `author` and `license`

- CHANGELOG.md
- cmds/core/eval.js
- cmds/core/exec.js
- cmds/core/run.js
- docs/content/en/Getting Started/Advanced Usage.md
- lisp/_prepare.el
- src/util.js
Few commands don't need Eask-file for execution,
```
eask init from=cask
eask keywords
eask generate license
```
, etc.
> feat(special): Allow few commands' execution without any Eask-file

- CHANGELOG.md
- cmds/core/cat.js
- docs/content/en/Getting Started/Basic Usage.md
- docs/content/en/Getting Started/Commands and options.md
- lisp/_prepare.el
- lisp/core/cat.el
- lisp/core/concat.el
- lisp/generate/license.el
- lisp/lint/checkdoc.el
- lisp/lint/declare.el
- lisp/lint/elint.el
- test/commands/local/run.sh
View filename(s),
```
eask cat <pattterns> [--n]
```
> feat(cat): Add command cat

- lisp/_prepare.el
- lisp/core/info.el
- lisp/core/upgrade.el
- lisp/extern/ansi.el
- test/development/compat.el
Make sure uses latest [ansi.el](https://github.com/rejeep/ansi.el).
> chore(ansi): Update ansi.el

- CHANGELOG.md
- lisp/_prepare.el
- lisp/core/cat.el
- lisp/core/install.el
- lisp/core/reinstall.el
- lisp/core/uninstall.el
- lisp/test/activate.el
Improve overall UX for package transaction.
> feat(package): Improve messages while processing package transaction

- CHANGELOG.md
- cmds/core/cat.js
- cmds/core/concat.js
- cmds/core/install-deps.js
- docs/content/en/Getting Started/Basic Usage.md
- eask
- src/util.js
Hide some commands and options by default.
> feat: Add use of `--show-hidden` option

- CHANGELOG.md
- cmds/generate/ignore.js
- docs/content/en/Development API/_index.md
- docs/content/en/Getting Started/Commands and options.md
- lisp/_prepare.el
- lisp/core/cat.el
- lisp/generate/ignore.el
- lisp/generate/license.el
- test/commands/local/run.sh
New command:
```
$ eask generate ignore elisp -o .elpaignore
```
> feat(generate): Add command to generate ignore file

- docs/content/en/Getting Started/Quick Start.md
- lisp/_prepare.el
- lisp/core/status.el
Example output
```
In the development (./) environment
Your emacs home is point to d:/_workspace/openai/.eask/29.0.60/
System:
Emacs version          29.0.60
Invocation             c:/Program Files/Emacs/emacs-29.0.60/bin/
Build No.              1
System configuration   x86_64-w64-mingw32
Build time             2023-03-10
System type            windows-nt
Environment:
Emacs directory        d:/_workspace/openai/.eask/29.0.60/
ELPA directory         d:/_workspace/openai/.eask/29.0.60/elpa
early-init.el          d:/_workspace/openai/.eask/29.0.60/early-init.el
init.el                d:/_workspace/openai/.eask/29.0.60/init.el
custom.el              d:/_workspace/openai/.eask/29.0.60/custom.el
Eask-file:
Eask file              d:/_workspace/openai/Eask
Eask-file Count        1
(Total of 13 …
```
> feat(UX): Improve status command's output

- CHANGELOG.md
- lisp/_prepare.el
- lisp/core/eval.el
- lisp/core/exec.el
- lisp/core/install-deps.el
- lisp/core/install.el
- lisp/core/reinstall.el
- lisp/core/run.el
- lisp/core/uninstall.el
- lisp/link/add.el
- lisp/lint/license.el
> fix(UX): Use ascii if unicode not displayable

- cmds/core/init.js
- lisp/_prepare.el
- lisp/help/init/keg
- lisp/init/keg.el
- test/development/compat.el
Add init from `Keg`-file.
Usage:
```
eask init --from keg
```
> feat(init): Add option to init from Keg-file

- CHANGELOG.md
- cmds/core/init.js
- docs/content/en/Getting-Started/Commands-and-options.md
- docs/content/zh-TW/Getting-Started/Commands-and-options.md
- lisp/_prepare.el
- lisp/help/init/source
- lisp/init/source.el
You can now create Eask-file by an elisp file:
```
eask init --from source /path/to/source.el
```
> feat: Init from source file

- CHANGELOG.md
- cmds/core/source.js
- cmds/source/add.js
- cmds/source/delete.js
- cmds/source/list.js
- docs/content/en/Getting-Started/Basic-Usage/_index.md
- docs/content/en/Getting-Started/Commands-and-options.md
- docs/content/en/Getting-Started/Introduction.md
- docs/content/zh-TW/Getting-Started/Basic-Usage/_index.md
- docs/content/zh-TW/Getting-Started/Commands-and-options.md
- lisp/_prepare.el
- lisp/core/archives.el
- lisp/help/source/add
- lisp/help/source/delete
- lisp/source/add.el
- lisp/source/delete.el
- lisp/source/list.el
- src/util.js
- test/commands/local/run.sh
```
$ eask source --help
```
```
$ eask source add <name> [path]
```
```
$ eask source delete <name>
```
```
$ eask source list
```
> feat(source): Add source and its subcommands

- CHANGELOG.md
- cmds/core/repl.js
- docs/content/en/Getting-Started/Commands-and-options.md
- docs/content/zh-TW/Getting-Started/Commands-and-options.md
- lisp/_prepare.el
- lisp/core/repl.el
- test/checker/dsl/Eask
- test/color/Eask
- test/commands/exec/Eask
- test/commands/outdated_upgrade/Eask
- test/commands/search/Eask
- test/commands/test/buttercup/Eask
- test/commands/test/ert-runner/Eask
- test/commands/test/ert/Eask
- test/error/Eask
- test/fixtures/mini.emacs.pkg.1/Eask
- test/fixtures/mini.emacs.pkg.2/Eask
- test/options/Eask
Start the Elips REPL:
```
$ eask repl
```
> feat(repl): Add the Elisp REPL command

- .github/workflows/build.yml
- .gitignore
> fix(build.yml): Use tar for unix-like system

- CHANGELOG.md
- cmds/core/format.js
- cmds/core/lint.js
- cmds/core/test.js
- cmds/format/elfmt.js
- cmds/format/elisp-autofmt.js
- docs/content/Getting-Started/Basic-Usage/_index.en.md
- docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md
- docs/content/Getting-Started/Commands-and-options/_index.en.md
- docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md
- lisp/format/elfmt.el
- lisp/format/elisp-autofmt.el
- lisp/help/format/elfmt
- lisp/help/format/elisp-autofmt
- test/commands/local/run.sh
New commands for formatting:
```
$ eask fmt elisp-autofmt
```
```
$ eask fmt elfmt
```
> feat(fmt): Add formatters

- .github/workflows/test_ecukes.yml
- CHANGELOG.md
- Makefile
- README.md
- cmds/test/ecukes.js
- docs/content/Getting-Started/Commands-and-options/_index.en.md
- docs/content/Getting-Started/Commands-and-options/_index.zh-tw.md
- lisp/test/buttercup.el
- lisp/test/ecukes.el
- lisp/test/melpazoid.el
- test/commands/test/ecukes/Eask
- test/commands/test/ecukes/run.sh
New command:
```
$ eask test ecukes
```
> feat(test): Add built-in ecukes test command

- webinstall/install.sh
For https://github.com/emacs-eask/eask/issues/5.
> fix: Webinstall on Linux/macOS

- CHANGELOG.md
- cmds/core/docker.js
- cmds/core/emacs.js
- cmds/core/exec.js
- cmds/core/outdated.js
- docs/content/Getting-Started/Basic-Usage/_index.en.md
- docs/content/Getting-Started/Basic-Usage/_index.zh-tw.md
- eask
- lisp/core/outdated.el
- test/commands/local/run.sh
- test/options/run.sh
Print error for unknown arguments or options, etc.
> feat(eask): Use strict option

- .github/workflows/build.yml
- package-lock.json
- package.json
Trying forked version of `pkg` --- https://github.com/yao-pkg/pkg.
> ci: Try forked pkg to fix arm64 build

- .github/workflows/analyze.yml
- .github/workflows/build.yml
- .github/workflows/compat.yml
- .github/workflows/compile.yml
- .github/workflows/config.yml
- .github/workflows/deprecated/color.yml
- .github/workflows/deprecated/error.yml
- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/emacs.yml
- .github/workflows/exec.yml
- .github/workflows/exit_status.yml
- .github/workflows/global.yml
- .github/workflows/install.yml
- .github/workflows/link.yml
- .github/workflows/local.yml
- .github/workflows/options.yml
- .github/workflows/outdated_upgrade.yml
- .github/workflows/search.yml
- .github/workflows/test_buttercup.yml
- .github/workflows/test_ecukes.yml
- .github/workflows/test_ert-runner.yml
- .github/workflows/test_ert.yml
Attempt to address https://github.com/emacs-eask/cli/pull/310#issuecomment-2744418918.
> ci: Remove unnecessary run on docs
